# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mana-signals',
                'doc_host': 'https://jstranik.github.io',
                'git_url': 'https://github.com/jstranik/mana-signals',
                'lib_path': 'mana_signals'},
  'syms': {'mana_signals.core': {'mana_signals.core.foo': ('core.html#foo', 'mana_signals/core.py')}}}
